apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmos-service-account
  namespace: todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
        azure.workload.identity/use: "true" # Injects the Workload Identity webhook
    spec:
      serviceAccountName: cosmos-service-account
      containers:
      - name: app
        image: mcr.microsoft.com/k8s/asodemos/cosmostodo:latest
        env:
          - name: CosmosDB__Account
            valueFrom:
              secretKeyRef:
                # This is the secret created by ASO associated with the CosmosDB Account.
                name: todo-app-sqldb-connection-settings
                key: documentEndpoint
                optional: false
          - name: CosmosDB__DatabaseName
            value: "todo-app-sql-db"
          - name: CosmosDB__ContainerName
            value: "todo-app-sql-container"
          - name: AZURE_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                key: clientId
                name: todo-app-identity-settings # This is the configmap created by ASO associated with the Managed Identity. See the UserAssignedIdentity resource for more details.
                optional: false
        ports:
        - containerPort: 80
          name: webserver
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: todo-app
