apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: todo-app-rg
  namespace: todo
  labels:
    infra: azure
spec:
  location: eastus
---
# Here's the identity which will be used by the app
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: todo-app-identity
  namespace: todo
  labels:
    infra: azure
spec:
  location: eastus
  owner:
    name: todo-app-rg
  operatorSpec:
    configMaps:  # Exporting the identities principalId/clientId to be consumed by the application pod
      principalId:
        name: todo-app-identity-settings
        key: principalId
      clientId:
        name: todo-app-identity-settings
        key: clientId
---
apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: todo-app-fic
  namespace: todo
  labels:
    infra: azure
spec:
  owner:
    name: todo-app-identity
  audiences:
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/
  issuer: ${AKS_OIDC_ISSUER}
  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:todo:cosmos-service-account
---
apiVersion: documentdb.azure.com/v1api20210515
kind: DatabaseAccount
metadata:
  name: todo-app-sqldb
  namespace: todo
  labels:
    infra: azure
spec:
  location: eastus
  locations:
    - locationName: eastus
  owner:
    name: todo-app-rg
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  operatorSpec:
    secrets:
      documentEndpoint:  # Also exporting the endpoint of the CosmosDB for consumption by the application pod
        name: todo-app-sqldb-connection-settings
        key: documentEndpoint
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabase
metadata:
  name: todo-app-sql-db
  namespace: todo
  labels:
    infra: azure
spec:
  location: eastus
  owner:
    name: todo-app-sqldb
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: todo-app-sql-db
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabaseContainer
metadata:
  name: todo-app-sql-container
  namespace: todo
  labels:
    infra: azure
spec:
  location: eastus
  owner:
    name: todo-app-sql-db
  resource:
    id: todo-app-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlRoleAssignment
metadata:
  name: todo-app-role-assignment
  namespace: todo
  labels:
    infra: azure
spec:
  owner:
    name: todo-app-sqldb
  principalIdFromConfig:  # Granting access to the identity created above
    name: todo-app-identity-settings
    key: principalId
  # This RoleDefinition corresponds to "Cosmos DB Built-in Data Contributor". See https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#built-in-role-definitions for more.
  roleDefinitionId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${APP_NAME}-rg/providers/Microsoft.DocumentDB/databaseAccounts/todo-app-sqldb/sqlRoleDefinitions/00000000-0000-0000-0000-000000000002
  scope: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${APP_NAME}-rg/providers/Microsoft.DocumentDB/databaseAccounts/todo-app-sqldb
