apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: cool-website-rg
  namespace: default
spec:
  location: westcentralus
---
apiVersion: storage.azure.com/v1alpha1api20210401
kind: StorageAccount
metadata:
  name: coolstorageaso
  namespace: default
spec:
  location: westcentralus
  kind: BlobStorage
  sku:
    name: Standard_LRS
  owner:
    name: cool-website-rg
  accessTier: Hot
---
apiVersion: storage.azure.com/v1alpha1api20210401
kind: StorageAccountsBlobService
metadata:
  name: blobservice
  namespace: default
spec:
  owner:
    name: coolstorageaso
---
apiVersion: storage.azure.com/v1alpha1api20210401
kind: StorageAccountsBlobServicesContainer
metadata:
  name: staticcontent
  namespace: default
spec:
  owner:
    name: blobservice
---
apiVersion: cache.azure.com/v1alpha1api20201201
kind: Redis
metadata:
  name: coolredis
  namespace: default
spec:
  location: westcentralus
  owner:
    name: cool-website-rg
  sku:
    family: P
    name: Premium
    capacity: 1
  # This section doesn't work on alpha-6 but will in the upcoming beta release
  # operatorSpec:
  #   # Just a note: these are secrets generated by Azure, we're going to go get them and put them someplace useful for our pretend service
  #   secrets:
  #     hostName:
  #       name: redisconnection-secret
  #       key: hostName
  #     sslPort:
  #       name: redisconnection-secret
  #       key: port
  #     primaryKey:
  #       name: redisconnection-secret
  #       key: key
  enableNonSslPort: false
  minimumTlsVersion: "1.2"
  redisConfiguration:
    maxmemory-delta: "10"
    maxmemory-policy: allkeys-lru
  redisVersion: "6"
---
apiVersion: cache.azure.com/v1alpha1api20201201
kind: RedisFirewallRule
metadata:
  name: fw1
  namespace: default
spec:
  owner:
    name: coolredis
  startIP: 1.2.3.4
  endIP: 1.2.3.4
